#!/usr/bin/env bash

# determine the project directory based on the location of this script
SCRIPTDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJDIR="$(dirname "${SCRIPTDIR}")"

function findexe {
    exe=$1

    printf "Searching for ${exe}..."
    dir=$(/usr/bin/which ${exe} 2>/dev/null)
    if [ "${dir}" == "" ]
    then
        printf " not found!\n"
        return 1
    else
        printf " found at ${dir}\n"
        return 0
    fi
}

findexe cmake || exit 1

cd "${PROJDIR}"

if [ "$1" == "clean" ]
then
    rm -rf build/*
    shift
fi

cmake ${options} -S . -B build $@

exit 0
